src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PropertyRepository::class)]
class Property
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?float $surface = null;

    #[ORM\ManyToOne(inversedBy: 'properties')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $owner = null;

    #[ORM\ManyToOne(inversedBy: 'properties')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\ManyToOne(inversedBy: 'properties')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Payment $payment = null;

    #[ORM\OneToMany(mappedBy: 'property', targetEntity: Visit::class)]
    private Collection $visits;

    #[ORM\OneToMany(mappedBy: 'property', targetEntity: Picture::class)]
    private Collection $pictures;

    #[ORM\ManyToMany(targetEntity: Favorite::class, mappedBy: 'property')]
    private Collection $favorites;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 255)]
    private ?string $zipcode = null;

    #[ORM\Column]
    private ?int $Room = null;

    public function __construct()
    {
        $this->visits = new ArrayCollection();
        $this->pictures = new ArrayCollection();
        $this->favorites = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getSurface(): ?float
    {
        return $this->surface;
    }

    public function setSurface(float $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getPayment(): ?Payment
    {
        return $this->payment;
    }

    public function setPayment(?Payment $payment): self
    {
        $this->payment = $payment;

        return $this;
    }

    /**
     * @return Collection<int, Visit>
     */
    public function getVisits(): Collection
    {
        return $this->visits;
    }

    public function addVisit(Visit $visit): self
    {
        if (!$this->visits->contains($visit)) {
            $this->visits->add($visit);
            $visit->setProperty($this);
        }

        return $this;
    }

    public function removeVisit(Visit $visit): self
    {
        if ($this->visits->removeElement($visit)) {
            // set the owning side to null (unless already changed)
            if ($visit->getProperty() === $this) {
                $visit->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Picture>
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures->add($picture);
            $picture->setProperty($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getProperty() === $this) {
                $picture->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Favorite>
     */
    public function getFavorites(): Collection
    {
        return $this->favorites;
    }

    public function addFavorite(Favorite $favorite): self
    {
        if (!$this->favorites->contains($favorite)) {
            $this->favorites->add($favorite);
            $favorite->addProperty($this);
        }

        return $this;
    }

    public function removeFavorite(Favorite $favorite): self
    {
        if ($this->favorites->removeElement($favorite)) {
            $favorite->removeProperty($this);
        }

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    public function setZipcode(string $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getHalfAddress(): string
    {
        return $this->getCity() . ' , ' . $this->getZipcode();
    }

    public function getFullAddress(): string
    {
        return $this->getAddress() . ' , ' .$this->getCity() . ' , ' . $this->getZipcode();
    }

    public function getRoom(): ?int
    {
        return $this->Room;
    }

    public function setRoom(int $Room): self
    {
        $this->Room = $Room;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $lastName = null;

    #[ORM\Column(length: 255)]
    private ?string $firstName = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $phoneNumber = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $profilePicture = null;

    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Property::class)]
    private Collection $properties;

    #[ORM\OneToMany(mappedBy: 'visitor', targetEntity: Visit::class)]
    private Collection $visits;


    public function __construct()
    {
        $this->properties = new ArrayCollection();
        $this->visits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(?string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profilePicture;
    }

    public function setProfilePicture(?string $profilePicture): self
    {
        $this->profilePicture = $profilePicture;

        return $this;
    }

    /**
     * @return Collection<int, Property>
     */
    public function getProperties(): Collection
    {
        return $this->properties;
    }

    public function addProperty(Property $property): self
    {
        if (!$this->properties->contains($property)) {
            $this->properties->add($property);
            $property->setOwner($this);
        }

        return $this;
    }

    public function removeProperty(Property $property): self
    {
        if ($this->properties->removeElement($property)) {
            // set the owning side to null (unless already changed)
            if ($property->getOwner() === $this) {
                $property->setOwner(null);
            }
        }

        return $this;
    }
    

    public function getFullName(): string
    {
        return $this->getFirstName() . ' ' . $this->getLastName();
    }

    /**
     * @return Collection<int, Visit>
     */
    public function getVisits(): Collection
    {
        return $this->visits;
    }

    public function addVisit(Visit $visit): self
    {
        if (!$this->visits->contains($visit)) {
            $this->visits->add($visit);
            $visit->setVisitor($this);
        }

        return $this;
    }

    public function removeVisit(Visit $visit): self
    {
        if ($this->visits->removeElement($visit)) {
            // set the owning side to null (unless already changed)
            if ($visit->getVisitor() === $this) {
                $visit->setVisitor(null);
            }
        }

        return $this;
    }

}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class PropertyType extends AbstractType
{
    const Rooms = [
        '0 pièce' => 0,
        '1 pièce' => 1,
        '2 pièces' => 2,
        '3 pièces' => 3,
        '4 pièces' => 4,
        '5 pièces' => 5,
        '6 pièces' => 6,
        '7 pièces' => 7,
        '8 pièces' => 8,
        '9 pièces' => 9,
        '10 pièces et plus' => 10,
    ];
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom de la propriété'
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Description'
            ])
            ->add('price', TextType::class, [
                'label' => 'Prix'
            ])
            ->add('surface', TextType::class, [
                'label' => 'Surface'
            ])
            ->add('city', TextType::class, [
                'label' => 'Ville'
            ])
            ->add('zipCode', TextType::class, [
                'label' => 'Code postal'
            ])
            ->add('address', TextType::class, [
                'label' => 'Adresse'
            ])
            ->add('category', EntityType::class, [
                'class' => 'App\Entity\Category',
                'choice_label' => 'name',
                'multiple' => false,
                'label' => 'Catégorie'
            ])
            ->add('room', ChoiceType::class, [
                'required' => true,
                'label' => 'Pièces',
                'placeholder' => 'Nombre de pièces',
                'choices' => self::Rooms,
            ])
            ->add('payment',EntityType::class, [
                'class' => 'App\Entity\Payment',
                'choice_label' => 'name',
                'multiple' => false,
                'label' => 'Durée'
            ])
            ->add('pictures', FileType::class, [
                'multiple' => true,
                'attr' => ['accept' => 'image/*'],
                'mapped' => false,
                'required' => false,
                'label' => 'Photos'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
        ]);
    }
}

templates/property/_card.html.twig
<article>
    <div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow">
        <a href="{{ path('app_property_show',{'id' : property.id}) }}" class="flex items-center justify-center">
            {% if property.pictures|length > 0 %}
                <img src="{{ asset(property_url ~ '/' ~ property.pictures[0].url) }}" alt="picture"
                     class="rounded-t-lg h-56  w-full">
            {% else %}
                <img src="{{ asset('uploads/property/nopicture.jpg') }}" alt="picture" class="rounded-t-lg">
            {% endif %}
        </a>
        <div class="p-5">
            <a href="{{ path('app_property_show',{'id' : property.id}) }}">
                <h5 class="mb-2 text-xl font-bold tracking-tight text-gray-900">{{ property.name }}</h5>
            </a>
            <div class="mb-3 font-normal text-gray-700 flex flex-row">
                <p class="mr-2">{{ property.city }}</p>
                <p>{{ property.zipcode }}</p>
            </div>
            <p class="mb-3 font-normal text-gray-700">{{ property.price }} €</p>
            <div class='grid grid-cols-2'>
                <p class="mb-3 font-normal text-gray-700">{{ property.surface }} m²</p>
                <p class="mb-3 font-normal text-gray-700">{{ property.room }} pièces</p>
            </div>
            <a href="{{ path('app_property_show',{'id' : property.id}) }}"
               class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800">
                Voir en détail
                <svg aria-hidden="true" class="w-4 h-4 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20"
                     xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                          d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
                          clip-rule="evenodd"></path>
                </svg>
            </a>
        </div>
    </div>
</article>

templates/property/_delete_form.html.twig
<form method="post" action="{{ path('app_property_delete', {'id': property.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ property.id) }}">
    <button class="btn">Delete</button>
</form>

templates/property/_filter.html.twig
{{ form_start(filterForm, {'action': path('property_list')}) }}
        {{ form_row(filterForm.city , {'attr': {'class': 'rounded-lg w-52'}}) }}
        {{ form_row(filterForm.zipcode,{'attr': {'class': 'rounded-lg w-52'}}) }}
        {{ form_row(filterForm.minPrice,{'attr': {'class': 'rounded-lg w-52'}}) }}
        {{ form_row(filterForm.maxPrice,{'attr': {'class': 'rounded-lg w-52'}}) }}
        {{ form_row(filterForm.minSurface,{'attr': {'class': 'rounded-lg w-52'}}) }}
        {{ form_row(filterForm.maxSurface,{'attr': {'class': 'rounded-lg w-52'}}) }}
        {{ form_row(filterForm.minRoom,{'attr': {'class': 'rounded-lg w-52'}}) }}
        {{ form_row(filterForm.maxRoom,{'attr': {'class': 'rounded-lg w-52'}}) }}
        {{ form_row(filterForm.category,{'attr': {'class': 'rounded-lg w-52'}}) }}
        {{ form_row(filterForm.payment,{'attr': {'class': 'rounded-lg w-52'}}) }}
    <div class="flex justify-center items-center">
        <button type="submit" class="bg-valid border-2 border-gray-400 rounded-lg h-12 w-24">Rechercher</button>
    </div>
{{ form_end(filterForm) }}

templates/property/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Property{% endblock %}

{% block body %}
    <section>
        <div class="flex flex-col justify-center items-center">
            <h2>Modifier les informations de votre propriété</h2>

            {{ include('property/_form.html.twig', {'button_label': 'Update'}) }}

            <a href="{{ path('profile', {'id': app.user.id} ) }}"
               class="text-white bg-main font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">Retour a
                votre profil</a>
        </div>
    </section>
{% endblock %}

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Property index{% endblock %}

{% block body %}
    <h1>Property index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                <th>Surface</th>
                <th>City</th>
                <th>Address</th>
                <th>Zip Code</th>
                <th>Owner</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for property in properties %}
            <tr>
                <td>{{ property.id }}</td>
                <td>{{ property.name }}</td>
                <td>{{ property.description }}</td>
                <td>{{ property.price }}</td>
                <td>{{ property.surface }}</td>
                <td>{{ property.city }}</td>
                <td>{{ property.address }}</td>
                <td>{{ property.zipCode }}</td>
                <td>{{ property.owner.fullName }}</td>

                <td>
                    <a href="{{ path('app_property_show', {'id': property.id}) }}">show</a>
                    <a href="{{ path('app_property_edit', {'id': property.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_property_new') }}">Create new</a>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Property{% endblock %}

{% block body %}
    <section>
        <div class="flex justify-between">
            <h2>{{ property.name }}</h2>
            {% if app.user %}
                {% if app.user.id != property.owner.id %}
                    <div class="flex justify-center items-center">
                        <a href="{{ path('ajoutfavori',{'id':property.id}) }}">
                            <div class="flex justify-center items-center bg-gray-100 rounded-full h-14 w-14">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
                                    <path fill="none" d="M0 0h24v24H0z"/>
                                    <path d="M12 18.26l-7.053 3.948 1.575-7.928L.587 8.792l8.027-.952L12 .5l3.386 7.34 8.027.952-5.935 5.488 1.575 7.928L12 18.26zm0-2.292l4.247 2.377-.949-4.773 3.573-3.305-4.833-.573L12 5.275l-2.038 4.42-4.833.572 3.573 3.305-.949 4.773L12 15.968z"/>
                                </svg>
                            </div>
                        </a>
                    </div>
                {% else %}
                    <div class="flex flex-row justify-center items-center gap-2 ">
                        <a href="{{ path('app_property_edit',{'id': property.id}) }}">
                            <div class="flex justify-center items-center">
                                <div class="flex justify-center items-center bg-gray-100 rounded-full h-14 w-14">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
                                        <path d="M16.7574 2.99666L14.7574 4.99666H5V18.9967H19V9.2393L21 7.2393V19.9967C21 20.5489 20.5523 20.9967 20 20.9967H4C3.44772 20.9967 3 20.5489 3 19.9967V3.99666C3 3.44438 3.44772 2.99666 4 2.99666H16.7574ZM20.4853 2.09717L21.8995 3.51138L12.7071 12.7038L11.2954 12.7062L11.2929 11.2896L20.4853 2.09717Z"
                                              fill="#000"></path>
                                    </svg>
                                </div>
                            </div>
                        </a>
                        <form method="post" action="{{ path('app_property_delete', {'id': property.id}) }}"
                              onsubmit="return confirm('Are you sure you want to delete this item?');">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ property.id) }}">
                            <button class="btn">
                                <div class="flex justify-center items-center">
                                    <div class="flex justify-center items-center bg-gray-100 rounded-full h-14 w-14">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24"
                                             height="24">
                                            <path d="M7 4V2H17V4H22V6H20V21C20 21.5523 19.5523 22 19 22H5C4.44772 22 4 21.5523 4 21V6H2V4H7ZM6 6V20H18V6H6ZM9 9H11V17H9V9ZM13 9H15V17H13V9Z"
                                                  fill="#000">
                                            </path>
                                        </svg>
                                    </div>
                                </div>
                            </button>
                        </form>
                    </div>
                {% endif %}
            {% else %}
                <a href="{{ path('app_login') }}"
                   class="flex jusitfy-center items-center w-56 text-blue-500 block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-red-400 md:p-0">Connecter
                    vous pour ajouter aux favoris</a>
            {% endif %}
        </div>
        <div class="grid grid-cols-1 lg:grid-cols-4 mb-12">
            {% if property.pictures|length > 0 %}
                <div id="carrousel" class="col-span-3 mb-4">
                    <div id="container" class="flex items-center justify-center">
                        {% for picture in property.pictures %}
                            <img src="{{ asset(property_url ~ '/' ~ picture.url) }}" alt="picture"
                                 class="hidden w-full h-[400px]">
                        {% endfor %}
                    </div>
                    <img src="{{ asset('picture/icons8-flèche-droite-90.png') }}" alt="Prev" class="bouton" id="prev">
                    <img src="{{ asset('picture/icons8-flèche-droite-90.png') }}" alt="Next" class="bouton" id="next">
                </div>
            {% else %}
                <div id="carrousel" class="col-span-3 bg-white mb-4">
                    <div id="container" class="flex items-center justify-center">
                        <img src="{{ asset('uploads/property/nopicture.jpg') }}" alt="picture"
                             class="hidden w-[250] h-[250]">
                    </div>
                </div>
            {% endif %}
            <div class="ml-16">
                <h3 class="mb-4">Superficie :</h3>
                <p class="text-2xl mb-2">{{ property.surface }} m²</p>
                <h3 class="mb-4">Prix :</h3>
                <p class="text-2xl  mb-2">{{ property.price }} €</p>
                <h3 class="mb-4">Mode de payement :</h3>
                <p class="capitalize text-xl">{{ property.payment.name }}</p>
            </div>
        </div>
        <div class="mb-8">
            <div class="mb-6">
                <h3>Description :</h3>
                <p>{{ property.description }}</p>
            </div>
            <div class="mb-6">
                <h3 class="mb-4">Adresse :</h3>
                <p>{{ property.halfAddress }}</p>
            </div>
        </div>
        {% if visits|length > 0 %}
            <div class="mb-8">
                <h3 class="mb-4">Futur Visites :</h3>
                <div class="relative overflow-x-auto">
                    <table class="w-full text-sm text-left text-gray-500">
                        <thead class="text-xs text-gray-700 uppercase bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3">
                                Début de la visite
                            </th>
                            <th scope="col" class="px-6 py-3">
                                Fin de la visite
                            </th>
                            <th scope="col" class="px-6 py-3">
                                Visiteur ?
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for visit in visits %}
                            <tr class="bg-white border-b">
                                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                                    <time datetime="{{ visit.dateStart|date('Y-m-d h:i') }}">
                                        {{ visit.dateStart|date('l jS \\o\\f F  \\a\\t g:i a') }}
                                    </time>
                                </th>
                                <td class="px-6 py-4">
                                    <time datetime="{{ visit.dateEnd|date('Y-m-d h:i') }}">
                                        {{ visit.dateEnd|date('l jS \\o\\f F  \\a\\t g:i a') }}
                                    </time>
                                </td>
                                <td>
                                    {% if visit.visitor %}
                                        <p>Il y a deja un visiteur</p>
                                    {% else %}
                                        {% if app.user %}

                                            {% if app.user.id != property.owner.id %}
                                                <a href="{{ path('app_visit_inscription',{'id' : visit.id}) }}"> Il n'y
                                                    pas de visiteur inscrivez vous !
                                                </a>
                                            {% else %}
                                                <p>Vous êtes le propriétaire</p>
                                            {% endif %}
                                        {% else %}
                                            <a href="{{ path('app_login') }}" class="">Connectez vous pour vous inscrire</a>
                                        {% endif %}
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>

            </div>
        {% endif %}
        <div class="mb-8">
            <h3>Propriétaire :</h3>
            <p>{{ property.owner.fullName }}</p>

        </div>
        <a href="{{ path('property_list') }}">
            <button type="button"
                    class="text-white bg-main font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">
                Retour
            </button>
        </a>
    </section>
    {% block javascripts %}
        <script type="text/javascript">
            document.body.onload = function () {
                let container = document.getElementById('container');
                let prev = document.getElementById('prev');
                let next = document.getElementById('next');

                container.firstElementChild.classList.remove('hidden');

                function nextSlide() {
                    let img = container.querySelector('img:not(.hidden)');
                    img.classList.add('hidden');
                    if (img.nextElementSibling) {
                        img.nextElementSibling.classList.remove('hidden');
                    } else {
                        container.firstElementChild.classList.remove('hidden');
                    }
                }

                function prevSlide() {
                    let img = container.querySelector('img:not(.hidden)');
                    img.classList.add('hidden');
                    if (img.previousElementSibling) {
                        img.previousElementSibling.classList.remove('hidden');
                    } else {
                        container.lastElementChild.classList.remove('hidden');
                    }
                }

                const interval = setInterval(nextSlide, 5000);
                next.addEventListener('click', () => {
                    clearInterval(interval);
                    nextSlide();
                });
                prev.addEventListener('click', () => {
                    clearInterval(interval);
                    prevSlide();
                });
            }
        </script>
    {% endblock %}
{% endblock %}