src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PropertyRepository::class)]
class Property
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?float $surface = null;

    #[ORM\ManyToOne(inversedBy: 'properties')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $owner = null;

    #[ORM\ManyToOne(inversedBy: 'properties')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\ManyToOne(inversedBy: 'properties')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Payment $payment = null;

    #[ORM\OneToMany(mappedBy: 'property', targetEntity: Visit::class)]
    private Collection $visits;

    #[ORM\OneToMany(mappedBy: 'property', targetEntity: Picture::class)]
    private Collection $pictures;

    #[ORM\ManyToMany(targetEntity: Favorite::class, mappedBy: 'property')]
    private Collection $favorites;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 255)]
    private ?string $zipcode = null;

    #[ORM\Column]
    private ?int $Room = null;

    public function __construct()
    {
        $this->visits = new ArrayCollection();
        $this->pictures = new ArrayCollection();
        $this->favorites = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getSurface(): ?float
    {
        return $this->surface;
    }

    public function setSurface(float $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getPayment(): ?Payment
    {
        return $this->payment;
    }

    public function setPayment(?Payment $payment): self
    {
        $this->payment = $payment;

        return $this;
    }

    /**
     * @return Collection<int, Visit>
     */
    public function getVisits(): Collection
    {
        return $this->visits;
    }

    public function addVisit(Visit $visit): self
    {
        if (!$this->visits->contains($visit)) {
            $this->visits->add($visit);
            $visit->setProperty($this);
        }

        return $this;
    }

    public function removeVisit(Visit $visit): self
    {
        if ($this->visits->removeElement($visit)) {
            // set the owning side to null (unless already changed)
            if ($visit->getProperty() === $this) {
                $visit->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Picture>
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures->add($picture);
            $picture->setProperty($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getProperty() === $this) {
                $picture->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Favorite>
     */
    public function getFavorites(): Collection
    {
        return $this->favorites;
    }

    public function addFavorite(Favorite $favorite): self
    {
        if (!$this->favorites->contains($favorite)) {
            $this->favorites->add($favorite);
            $favorite->addProperty($this);
        }

        return $this;
    }

    public function removeFavorite(Favorite $favorite): self
    {
        if ($this->favorites->removeElement($favorite)) {
            $favorite->removeProperty($this);
        }

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    public function setZipcode(string $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getHalfAddress(): string
    {
        return $this->getCity() . ' , ' . $this->getZipcode();
    }

    public function getFullAddress(): string
    {
        return $this->getAddress() . ' , ' .$this->getCity() . ' , ' . $this->getZipcode();
    }

    public function getRoom(): ?int
    {
        return $this->Room;
    }

    public function setRoom(int $Room): self
    {
        $this->Room = $Room;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $lastName = null;

    #[ORM\Column(length: 255)]
    private ?string $firstName = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $phoneNumber = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $profilePicture = null;

    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Property::class)]
    private Collection $properties;

    #[ORM\OneToMany(mappedBy: 'visitor', targetEntity: Visit::class)]
    private Collection $visits;


    public function __construct()
    {
        $this->properties = new ArrayCollection();
        $this->visits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(?string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profilePicture;
    }

    public function setProfilePicture(?string $profilePicture): self
    {
        $this->profilePicture = $profilePicture;

        return $this;
    }

    /**
     * @return Collection<int, Property>
     */
    public function getProperties(): Collection
    {
        return $this->properties;
    }

    public function addProperty(Property $property): self
    {
        if (!$this->properties->contains($property)) {
            $this->properties->add($property);
            $property->setOwner($this);
        }

        return $this;
    }

    public function removeProperty(Property $property): self
    {
        if ($this->properties->removeElement($property)) {
            // set the owning side to null (unless already changed)
            if ($property->getOwner() === $this) {
                $property->setOwner(null);
            }
        }

        return $this;
    }
    

    public function getFullName(): string
    {
        return $this->getFirstName() . ' ' . $this->getLastName();
    }

    /**
     * @return Collection<int, Visit>
     */
    public function getVisits(): Collection
    {
        return $this->visits;
    }

    public function addVisit(Visit $visit): self
    {
        if (!$this->visits->contains($visit)) {
            $this->visits->add($visit);
            $visit->setVisitor($this);
        }

        return $this;
    }

    public function removeVisit(Visit $visit): self
    {
        if ($this->visits->removeElement($visit)) {
            // set the owning side to null (unless already changed)
            if ($visit->getVisitor() === $this) {
                $visit->setVisitor(null);
            }
        }

        return $this;
    }

}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\Property;
use App\Form\ProfileUpdateType;
use App\Repository\FavoriteRepository;
use App\Repository\PropertyRepository;
use App\Repository\UserRepository;
use App\Repository\VisitRepository;
use App\Service\FileUploader;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    #[Route('/', name: 'homepage')]
    public function index(): Response
    {
        return $this->render('default/homepage.html.twig', [
        ]);
    }

    #[Route('/about', name: 'about')]
    public function about(): Response
    {
        return $this->render('default/about.html.twig', [
        ]);
    }

    #[Route('/profile/{id}', name: 'profile', requirements: ['id' => '\d+'])]
    #[IsGranted('ROLE_USER')]
    public function profile(int $id,
                            PropertyRepository $propertyRepository,
                            VisitRepository $visitRepository,
                            FavoriteRepository $favoriteRepository
    ): Response
    {
        $user = $this->getUser();
        $properties = $propertyRepository->findBy(['owner' => $user]);
        $favorite = $favoriteRepository->findOneBy(['user' => $user]);

        if ($user->getId() !== $id) {
            return $this->redirectToRoute('profile', ['id' => $user->getId()]);
        }

        return $this->render('default/profile.html.twig', [
            'user' => $user,
            'properties' => $properties,
            'visits' => $visitRepository->findFutureVisitOwner($user),
            'visitstodo' => $visitRepository->findFutureVisit($user),
            'favorite' => $favorite,
        ]);
    }

    #[Route('/profile/{id}/edit', name: 'profile_edit', requirements: ['id' => '\d+'], methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_USER')]
    public function profileEdit(int $id,
                                Request $request,
                                UserRepository $userRepository,
                                FileUploader $fileUploader
    ): Response
    {
        $user = $this->getUser();
        $form = $this->createForm(ProfileUpdateType::class, $user);
        $form->handleRequest($request);

        if ($user->getId() !== $id) {
            return $this->redirectToRoute('profile', ['id' => $user->getId()]);
        }

        if ($form->isSubmitted() && $form->isValid()) {
            $image = $form->get('profilePicture')->getData();
            if ($image) {
                $fileUploader->setTargetDirectory($this->getParameter('pp_directory'));
                $fileName = $fileUploader->upload($image);
                $user->setProfilePicture($fileName);
            }



            $userRepository->save($user, true);

            return $this->redirectToRoute('profile', ['id' => $user->getId()]);
        }

        return $this->render('default/update.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }
}

templates/default/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div style='background-image: url("{{ asset('picture/frontpage2.jpg') }}")' class="h-[400px] bg-cover bg-center py-20 mt-16">
        <div class="flex justify-center items-center flex-col">
            <h1 class="text-white mb-4">Accueil</h1>
            <h3 class="text-white">Find My Home</h3>
            <p class="text-white mb-8">Pour une semaine, un An, une Vie</p>
            <p class="text-white px-8 mb-4">Bonjour bienvenue sur notre site. Notre objectif vous facilitez les recherches pour
                trouver des biens immobiliers qui vous convient!</p>
            <a href="{{ path('app_login') }}" type="button"
               class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center mr-3 md:mr-0 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Voir les Propriétés</a>
        </div>
    </div>
    <section>
        <h2>Présentation</h2>
        <div class="pl-12">
            <p>Bienvenue sur le site Find My Home</p>
            <p>Vous êtes à la recherche d'un bien immobilier ?</p>
            <p>Find My Home est un site créé par Benjamin Forest alors Étudiant en développement web dans l'école de
                Digital Campus a Rennes</p>
            <p>Pour l'instant, c'est un projet d'étude pour pouvoir développer mes capacités et mon expérience dans le
                domaine de la création de site web</p>
            <p>Le site est encore en construction, mais il sera bientôt disponible pour vous aider dans vos recherches
                de biens immobilier</p>
            <p>Ce site web est développer en PHP avec le framework Symfony</p>
        </div>
        <h2>Fonctionnalités</h2>
        <div class="pl-12">
            <ul>
                <li>Créer un compte</li>
                <li>Ajouter des propriétés</li>
                <li>Voir les propriétés</li>
                <li>Créer des visites</li>
                <li>Voir les visites</li>
                <li>S'inscrire au visite</li>
                <li>Ajouter des propriétés en favoris</li>
                <li>Nous Contacter via mail</li>
            </ul>
        </div>
    </section>
{% endblock %}

templates/default/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil{% endblock %}

{% block body %}
    <section>
        <div class="grid grid-cols-3 pt-8 mb-8">
            <div>
                <h2 class="capitalize">{{ user.fullName }}</h2>
                <p class="pl-8 mb-4">{{ user.email }}</p>
                <div class="flex justify-center items-center w-36 text-white text-3xl bg-valid font-medium rounded-lg text-sm ml-8 px-5 py-2.5 text-center" >
                    <a href="{{ path('profile_edit', {'id': app.user.id}) }}">Mettre a jour votre profil</a>
                </div>
            </div>
            <div class="col-start-3">
                <div class="flex justify-center items-center">
                    {% if user.profilePicture %}
                    <img src="{{ asset('uploads/pp/' ~ user.profilePicture) }}" alt="Photo de profile"
                         class="rounded-full w-48 h-48 inline-grid">
                    {%else%}
                    <img src="{{ asset('uploads/pp/placeholderpp.png') }}" alt="Photo de profile"
                         class="rounded-full w-48 h-48 inline-grid">
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="mb-8">
            <div class="flex justify-between mb-4">
                <h3 class="mb-4">Mes biens :</h3>
                <div class="grid grid-cols-3 col-start-3">
                    <a href="{{ path('app_property_new') }}"
                       class="flex justify-center items-center text-white text-3xl col-start-3 bg-main  font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">
                        Ajouter un bien
                    </a>
                </div>
            </div>
            {% if properties %}
                <div class="grid grid-cols-1 md:grid-cols-3 gap-y-8 gap-x-4 mb-4">
                    {% for property in properties %}
                        {% include 'property/_card.html.twig' %}
                    {% endfor %}
                </div>
            {% else %}
                <h4 class="mb-4 ">Vous n'avez pas encore publié de bien</h4>
            {% endif %}
        </div>
        <div class="mb-8">
            <div class="flex justify-between mb-4">
                <h3 class="mb-4">Mes visites à faire :</h3>
                <div class="grid grid-cols-3 col-start-3">
                    <a href="{{ path('app_visit_new') }}"
                       class="flex justify-center items-center text-3xl text-white col-start-3 bg-main font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">
                        Créer une visite
                    </a>
                </div>
            </div>
            {% if visits %}
            <table class="w-full text-sm text-left text-gray-500 table-fixed overflow-x-auto">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50">
                <tr>
                    <th scope="col" class="px-6 py-3">
                        Nom du bien
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Début de la visite
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Fin de la visite
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Visiteur
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for visit in visits %}
                    <tr class="bg-white border-b">
                        <td class="px-6 py-4">
                            <a href="{{ path('app_property_show',{'id' : visit.property.id}) }}"
                               class="text-gray-900 font-medium hover:text-gray-600">
                                {{ visit.property.name }}
                            </a>
                        <td class="px-6 py-4">
                            <time datetime="{{ visit.dateStart|date('Y-m-d h:i') }}">
                                {{ visit.dateStart|date('l jS \\o\\f F  \\a\\t g:i a') }}
                            </time>
                        </td>
                        <td class="px-6 py-4">
                            <time datetime="{{ visit.dateEnd|date('Y-m-d h:i') }}">
                                {{ visit.dateEnd|date('l jS \\o\\f F  \\a\\t g:i a') }}
                            </time>
                        </td>
                        <td class="px-6 py-4">
                            <p class="text-gray-900 font-medium hover:text-gray-600">
                                {% if visit.visitor %}
                                {{ visit.visitor.fullName }}
                                {% else %}
                            <p class="text-gray-900 font-medium hover:text-gray-600">
                                Aucun visiteur
                            </p>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
            <h4>Vous n'avez pas encore créé de visite</h4>
        {% endif %}
        <div class="mb-8">
            <h3 class="mb-4">Mes visites a assister :</h3>
            {% dump visitstodo %}
            {% if visitstodo %}
            <table class="w-full text-sm text-left text-gray-500 table-fixed overflow-x-auto">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50">
                <tr>
                    <th scope="col" class="px-6 py-3">
                        Nom du bien
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Début de la visite
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Fin de la visite
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Adresse de la visite
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for visittodo in visitstodo %}
                    <tr class="bg-white border-b">
                        <td class="px-6 py-4">
                            <a href="{{ path('app_property_show',{'id' : visittodo.property.id}) }}"
                               class="text-gray-900 font-medium hover:text-gray-600">
                                {{ visittodo.property.name }}
                            </a>
                        <td class="px-6 py-4">
                            <time datetime="{{ visittodo.dateStart|date('Y-m-d h:i') }}">
                                {{ visittodo.dateStart|date('l jS \\o\\f F  \\a\\t g:i a') }}
                            </time>
                        </td>
                        <td class="px-6 py-4">
                            <time datetime="{{ visittodo.dateEnd|date('Y-m-d h:i') }}">
                                {{ visittodo.dateEnd|date('l jS \\o\\f F  \\a\\t g:i a') }}
                            </time>
                        </td>
                        <td class="px-6 py-4">
                            {{ visittodo.property.fullAddress }}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <p class="mb-4">Vous n'avez pas de visite a assister</p>
        {% endif %}
        <div class="pb-8">
            <h3 class="mb-4">Mes biens Favoris :</h3>
            {% dump favorite %}
            {% if favorite.property is null %}
                <div class="grid grid-cols-3 gap-y-8 mb-4">
                    {% for property in favorite[0].property %}
                        {% include 'property/_card.html.twig' %}
                    {% endfor %}
                </div>
            {% else %}
                <p>Vous n'avez pas encore de bien favoris</p>
            {% endif %}
        </div>

    </section>

{% endblock %}

templates/default/update.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil{% endblock %}

{% block body %}
    <section>

        <div class="flex flex-col justify-center items-center">
            <h2>Mettre a jour votre profil</h2>
        {{ form_start(form) }}
        {{ form_row(form.email, {'attr' : {'class': 'w-80 mb-4 shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg block w-full p-2.5','placeholder':'john.doe@gmail.com'}, 'label': 'Votre email'}) }}
        {{ form_row(form.plainPassword, {'attr' : {'class': 'w-80 mb-4 shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg block w-full p-2.5','placeholder':'password'}, 'label': 'Ton mot de passe'}) }}
        {{ form_row(form.lastName, {'attr' : {'class': 'w-80 mb-4 shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg block w-full p-2.5','placeholder':'Doe'}, 'label': 'Ton nom'}) }}
        {{ form_row(form.firstName, {'attr' : {'class': 'w-80 mb-4 shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg block w-full p-2.5','placeholder':'John'}, 'label': 'Ton prénom'}) }}
        {{ form_row(form.phoneNumber, {'attr' : {'class': 'w-80 mb-4 shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg block w-full p-2.5','placeholder':'0600000000'}, 'label': 'Ton numéro de téléphone'}) }}
        {{ form_row(form.profilePicture, {'attr' : {'class': 'w-80 mb-4 shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg block w-full p-2.5'}, 'label': 'Ta photo de profile'}) }}
        <div class="flex justify-center items-center">
            <button type="submit" class="bg-valid font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">Mettre a jour</button>
        </div>
        {{ form_end(form) }}
            <a href="{{ path('profile', {'id': app.user.id} ) }}" class="text-white bg-main font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">Retour a votre profil</a>
        </div>
    </section>
{% endblock %}